# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Generate Code
      run: python3 generate.py
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Install Formatter
      run: brew install mint
    - run: mint install apple/swift-format@release/5.7
    - run: mint run apple/swift-format@release/5.7  -i -r Sources/iOS-Bluetooth-Numbers-Database/Extensions
    - name: Commit changes
      run: |
        git config --global user.name 'Automatic Commit'
        git config --global user.email 'automatic-commit@github.com'
        git add .
        git commit -m 'Github Action: Format Code'
        git push
